# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React CI/CD

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [master]

env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          git config --global user.name $github_username
          git config --global user.email $github_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          github_email: 'nesdamien@gmail.com'
          github_username: 'Nestor-19'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}